project_id = "wybhtprxiwgzmpmnfceq"

[functions.test-smtp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.relance]
enabled = true
verify_jwt = true
import_map = "./functions/relance/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/relance/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/relance/*.html" ]
