[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  # Variables VITE_ pour React + Supabase
  VITE_SUPABASE_URL = "https://wybhtprxiwgzmpmnfceq.supabase.co"
  # VITE_SUPABASE_ANON_KEY = (à ajouter dans Netlify dashboard, jamais en clair)

# Redirect SPA pour React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  
